"""One clear entrypoint for local RAG operations and QA.

No implicit cloud calls, deployment, deletion or provider writes. Running a test
executes the selected existing test with its original safety boundaries.
"""
import argparse
from pathlib import Path
import runpy
import subprocess
import sys

# Keep generated bytecode out of the folders the PO browses. The private cache
# remains local to this process and workspace, not a machine-wide Python setting.
sys.pycache_prefix = str(Path(__file__).resolve().parent / '.local/python-cache')

from workspace import APP, ROOT, bootstrap, compose_file, named_file

RUNTIME_PROFILES = (
    'infrastructure/compose/runtime/compose.yaml', 'infrastructure/compose/runtime/compose.retrieval.yaml', 'infrastructure/compose/runtime/compose.semantic.yaml',
    'infrastructure/compose/runtime/compose.integrations.yaml', 'infrastructure/compose/labs/compose.gemini-rag.yaml', 'infrastructure/compose/runtime/compose.documents.yaml',
    'infrastructure/compose/runtime/compose.delivery.yaml', 'infrastructure/compose/observability/compose.observability.yaml', 'infrastructure/compose/resilience/compose.resilience.yaml',
    'infrastructure/compose/resilience/compose.resilience-integrations.yaml', 'infrastructure/compose/observability/compose.grafana.yaml',
)


def main():
    parser = argparse.ArgumentParser(description='RAG local: operações, testes e fila de cards')
    parser.add_argument('area', choices=['test', 'tool', 'cards', 'runtime', 'locate'])
    parser.add_argument('args', nargs=argparse.REMAINDER)
    args = parser.parse_args()
    bootstrap()
    if args.area == 'locate':
        if len(args.args) != 1:
            parser.error('Informe um nome de arquivo.')
        print(named_file(APP, args.args[0]))
        return 0
    if args.area == 'runtime':
        if not args.args or args.args[0] not in ('config', 'ps', 'up', 'logs'):
            parser.error('Use config, ps, up ou logs. Paradas e remoções não são implícitas.')
        command = ['docker', 'compose', '--project-directory', str(APP), '-p', 'rag-local-v2']
        for name in RUNTIME_PROFILES:
            command += ['-f', str(compose_file(name))]
        extra = ['-d', '--no-build', '--wait', '--wait-timeout', '480'] if args.args[0] == 'up' else []
        result = subprocess.run(command + [args.args[0]] + extra + args.args[1:], cwd=APP,
                                capture_output=True, text=True, encoding='utf8',
                                shell=False, creationflags=subprocess.CREATE_NO_WINDOW if sys.platform == 'win32' else 0)
        sys.stdout.write(result.stdout)
        sys.stderr.write(result.stderr)
        return result.returncode
    if args.area == 'cards':
        script = named_file(APP / 'tools', 'card_queue.py')
        tail = args.args or ['status']
    else:
        if not args.args:
            parser.error('Informe o nome do script existente.')
        filename = args.args[0]
        if not filename.endswith(('.py', '.ps1')):
            filename += '.py'
        script = named_file(APP / ('tests' if args.area == 'test' else 'tools'), filename)
        tail = args.args[1:]
    if script.suffix != '.py':
        parser.error('Scripts PowerShell são executados diretamente pelo terminal integrado.')
    sys.argv = [str(script), *tail]
    runpy.run_path(str(script), run_name='__main__')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
