# Exemplo gerado por `python -m cli transpile specs/agent.json`; não editar.
# tests/test_transpiler.py gera de novo e compara com este arquivo.
"""Generated by `python -m cli transpile` from agent.json. Do not edit by hand.

Declared here, from the spec, with Google ADK classes: the model, each LlmAgent (its tools, its
instruction, its output_key), the SequentialAgent that runs them, and the App that `adk run` and
`adk web` load (resumable: a tool call that asks for a confirmation pauses and resumes). Imported
from `runtime`, the transpiler's runtime library (interface 6, tested on its own, the same for every
spec):
- LiveOpenAPIToolset: ADK's OpenAPIToolset, built from an API's live /openapi.json on first use,
  on a host that ALLOWED_HOSTS allows;
- McpToolset: ADK's McpToolset, on a host that ALLOWED_HOSTS allows (checked on import);
- gemini: the model with retries (and the reserve model);
- require_api: stops this file on a runtime with another interface.
The App's plugins (ADK's BasePlugin), each with the kwargs the spec gives it: BookingPlugin from
runtime.plugin.
"""
from google.adk.agents import LlmAgent, SequentialAgent
from google.adk.apps import App, ResumabilityConfig
from google.adk.tools.mcp_tool.mcp_session_manager import SseConnectionParams

from runtime import LiveOpenAPIToolset, McpToolset, gemini, require_api
from runtime.plugin import BookingPlugin

require_api(6)  # a runtime with another interface stops here, with a clear message

# Gemini (GEMINI_MODEL in .env, or `-e GEMINI_MODEL=<model>` for one run, can replace it). A
# request it refuses with 429 (quota) or 503 (overloaded) goes at once to the reserve model,
# gemini-3.5-flash-lite, which retries 429/500/503 up to 5 times; the main model retries only a
# 500.
MODEL = gemini('gemini-3.5-flash', fallback='gemini-3.5-flash-lite')

extract = LlmAgent(
    name='extract',
    model=MODEL,
    instruction=(
        'Você lê pedidos médicos fictícios. Chame extract_exam_text com o nome do arquivo informado pelo usuário. '
        'Responda somente com os nomes de exames encontrados, um por linha. Ignore marcadores de dados pessoais como '
        '[NOME] ou [CPF] e não invente exames.'
    ),
    tools=[
        McpToolset(
            connection_params=SseConnectionParams(url='http://ocr:8001/sse'),
            tool_filter=['extract_exam_text'],
        ),
    ],
    output_key='exam_names',
)

search = LlmAgent(
    name='search',
    model=MODEL,
    instruction=(
        'Para cada exame da lista abaixo, chame search_exams com o nome do exame como foi lido, sem corrigir e sem '
        'marcadores ou conectivos (como "-" ou "e"), e fique com o resultado de maior score. Responda somente com '
        'JSON: uma lista de objetos {"code": ..., "name": ...}, sem texto extra. Omita exames sem resultado.\nExames:\n'
        '{exam_names?}'
    ),
    tools=[
        McpToolset(
            connection_params=SseConnectionParams(url='http://rag:8002/sse'),
            tool_filter=['search_exams'],
        ),
    ],
    output_key='exam_codes',
)

schedule = LlmAgent(
    name='schedule',
    model=MODEL,
    instruction=(
        'Agende os exames abaixo chamando a ferramenta que cria um agendamento (POST /appointments) com o corpo '
        '{"exams": <lista abaixo>}. Depois responda com o id e o status devolvidos pela API.\nExames:\n{exam_codes?}'
    ),
    tools=[
        LiveOpenAPIToolset(
            openapi_url='http://api:8000/openapi.json',
            base_url='http://api:8000',
            tool_filter=['create_appointment'],
        ),
    ],
    output_key='appointment',
)

root_agent = SequentialAgent(
    name='clinic_scheduler',
    sub_agents=[extract, search, schedule],
)
app = App(
    name='clinic_scheduler',
    root_agent=root_agent,
    plugins=[
        BookingPlugin(
            servers={
                'ocr': 'http://ocr:8001/sse',
                'rag': 'http://rag:8002/sse',
                'api': 'http://api:8000/openapi.json',
            },
            read='ocr.extract_exam_text',
            search='rag.search_exams',
            book='api.create_appointment',
            min_confidence=0.9,
            ask_from=0.7,
            ocr_floor_line=75,
            ocr_floor_short=85,
            ocr_floor_synonym=95,
            top_k=3,
        ),
    ],
    resumability_config=ResumabilityConfig(is_resumable=True),
)
