# Exemplo gerado por `python -m cli transpile specs/agent.json`; não editar.
# tests/test_transpiler.py gera de novo e compara com este arquivo.
"""Generated by `python -m cli transpile` from agent.json. Do not edit by hand.

Declared here, from the spec, with Google ADK classes: the model, one LlmAgent per step (its
tools, its instruction, its output_key), the confidence thresholds, the SequentialAgent and the
App that `adk run` and `adk web` load (resumable, so the question for an exam read with medium
confidence pauses and resumes the same booking call). Imported from `runtime`, the transpiler's
runtime library (interface 5, tested on its own, the same for every spec):
- BookingCallbacks: ADK callbacks that start the order from the session or the user's message, check
  in code every exam code the model proposes and write the final report;
- BookingPolicy: the thresholds below, as a typed value;
- LiveOpenAPIToolset: ADK's OpenAPIToolset, built from an API's live /openapi.json on first use,
  on a host that ALLOWED_HOSTS allows;
- McpToolset: ADK's McpToolset, on a host that ALLOWED_HOSTS allows (checked on import);
- gemini, guarded: the model with retries (and the reserve model), and the fixed rule put before each instruction;
- require_api: stops this file on a runtime with another interface.
"""
from google.adk.agents import LlmAgent, SequentialAgent
from google.adk.apps import App, ResumabilityConfig
from google.adk.tools.mcp_tool.mcp_session_manager import SseConnectionParams

from runtime import BookingCallbacks, BookingPolicy, LiveOpenAPIToolset, McpToolset, gemini, guarded, require_api

require_api(5)  # a runtime with another interface stops here, with a clear message

# Gemini (GEMINI_MODEL in .env, or `-e GEMINI_MODEL=<model>` for one run, can replace it). A
# request it refuses with 429 (quota) or 503 (overloaded) goes at once to the reserve model,
# gemini-3.5-flash-lite, which retries 429/500/503 up to 5 times; the main model retries only a
# 500.
MODEL = gemini('gemini-3.5-flash', fallback='gemini-3.5-flash-lite')
# An exam at or above min_confidence is booked; from ask_from up, only if the person says yes
# [s/N]; below, it is left out and reported. A line the OCR read (0-100) below its floor is never
# sure: ocr_floor_line, ocr_floor_short (3 letters or fewer), ocr_floor_synonym (an abbreviation
# of a longer name, such as "TGP"). top_k: results per search.
POLICY = BookingPolicy(
    min_confidence=0.9,
    ask_from=0.7,
    ocr_floor_line=75,
    ocr_floor_short=85,
    ocr_floor_synonym=95,
    top_k=3,
)
# One set of callbacks for every step; each acts only on its own tool. The reading tool gets only
# this run's file. Each search keeps its candidates. The booking tool receives only codes a search
# returned, each on its own piece of the order, by the POLICY above. The model only proposes.
CALLBACKS = BookingCallbacks(
    ocr_tool='extract_exam_text',
    search_tool='search_exams',
    booking_tool='create_appointment',
    policy=POLICY,
    ocr_url='http://ocr:8001/sse',
    search_url='http://rag:8002/sse',
    servers=['http://ocr:8001/sse', 'http://rag:8002/sse', 'http://api:8000/openapi.json'],
)

extract = LlmAgent(
    name='extract',
    model=MODEL,
    instruction=guarded(
        'Você lê pedidos médicos fictícios. Chame extract_exam_text com o nome do arquivo informado pelo usuário. '
        'Responda somente com os nomes de exames encontrados, um por linha. Ignore marcadores de dados pessoais como '
        '[NOME] ou [CPF] e não invente exames.'
    ),
    tools=[
        McpToolset(connection_params=SseConnectionParams(url='http://ocr:8001/sse'), tool_filter=['extract_exam_text']),
    ],
    before_model_callback=CALLBACKS.before_model,
    on_model_error_callback=CALLBACKS.model_failed,
    before_tool_callback=CALLBACKS.before_tool,
    after_tool_callback=CALLBACKS.after_tool,
    output_key='exam_names',
)

search = LlmAgent(
    name='search',
    model=MODEL,
    instruction=guarded(
        'Para cada exame da lista abaixo, chame search_exams com o nome do exame como foi lido, sem corrigir e sem '
        'marcadores ou conectivos (como "-" ou "e"), e fique com o resultado de maior score. Responda somente com '
        'JSON: uma lista de objetos {"code": ..., "name": ...}, sem texto extra. Omita exames sem resultado.\nExames:\n'
        '{exam_names}'
    ),
    tools=[McpToolset(connection_params=SseConnectionParams(url='http://rag:8002/sse'), tool_filter=['search_exams'])],
    before_agent_callback=CALLBACKS.fill_missing('exam_names'),
    before_model_callback=CALLBACKS.before_model,
    on_model_error_callback=CALLBACKS.model_failed,
    before_tool_callback=CALLBACKS.before_tool,
    after_tool_callback=CALLBACKS.after_tool,
    output_key='exam_codes',
)

schedule = LlmAgent(
    name='schedule',
    model=MODEL,
    instruction=guarded(
        'Agende os exames abaixo chamando a ferramenta que cria um agendamento (POST /appointments) com o corpo '
        '{"exams": <lista abaixo>}. Depois responda com o id e o status devolvidos pela API.\nExames:\n{exam_codes}'
    ),
    tools=[
        LiveOpenAPIToolset(
            openapi_url='http://api:8000/openapi.json',
            base_url='http://api:8000',
            tool_filter=['create_appointment'],
        ),
    ],
    before_agent_callback=CALLBACKS.fill_missing('exam_names', 'exam_codes'),
    before_model_callback=CALLBACKS.before_model,
    on_model_error_callback=CALLBACKS.model_failed,
    before_tool_callback=CALLBACKS.before_tool,
    after_tool_callback=CALLBACKS.after_tool,
    output_key='appointment',
)

# The order starts here (start_order: the image from the session or from the user's message, the
# servers' addresses and the image checked before any model turn) and ends in a report written from
# what the tools returned (report), never from the model's account of it.
root_agent = SequentialAgent(
    name='clinic_scheduler',
    sub_agents=[extract, search, schedule],
    before_agent_callback=CALLBACKS.start_order,
    after_agent_callback=CALLBACKS.report,
)
app = App(name='clinic_scheduler', root_agent=root_agent, resumability_config=ResumabilityConfig(is_resumable=True))
